name: Kernel Config - A12 5.10

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
      use_make:
        required: true
        type: boolean

jobs:
  build-kernels-a12:
    strategy:
      fail-fast: true
      matrix:
        include:
        - sub_level: "168"
          os_patch_level: "2023-04"
          revision: "r9"
        - sub_level: "198"
          os_patch_level: "2024-01"
          revision: "r17"
        - sub_level: "205"
          os_patch_level: "2024-03"
          revision: "r9"
        - sub_level: "209"
          os_patch_level: "2024-05"
          revision: "r13"
        - sub_level: "218"
          os_patch_level: "2024-08"
          revision: "r14"
        - sub_level: "226"
          os_patch_level: "2024-11"
          revision: "r9"
        - sub_level: "233"
          os_patch_level: "2025-02"
          revision: "r3"
        - sub_level: "236"
          os_patch_level: "2025-05"
          revision: "r3"
        - sub_level: "237"
          os_patch_level: "2025-06"
          revision: "r1"
        - sub_level: "X"
          os_patch_level: "lts"
          revision: "r1"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      revision: ${{ matrix.revision }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      use_make: ${{ inputs.use_make }}
      
