name: Build Kernel - A14

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs:
      kernelsu_variant:
        required: true
        type: string
      kernelsu_branch:
        required: true
        type: string
      kernelsu_branch_other:
        required: false
        type: string
      use_make:
        required: true
        type: boolean

jobs:
  build-kernels-a14-5-15:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "137"
            os_patch_level: "2024-01"
          - sub_level: "144"
            os_patch_level: "2024-03"
          - sub_level: "148"
            os_patch_level: "2024-05"
          - sub_level: "149"
            os_patch_level: "2024-06"
          - sub_level: "153"
            os_patch_level: "2024-07"
          - sub_level: "158"
            os_patch_level: "2024-08"
          - sub_level: "167"
            os_patch_level: "2024-11"
          - sub_level: "170"
            os_patch_level: "2025-01"
          - sub_level: "178"
            os_patch_level: "2025-03"
          - sub_level: "180"
            os_patch_level: "2025-05"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "5.15"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
      use_make: ${{ inputs.use_make }}

  build-kernels-a14-6-1:
    strategy:
      fail-fast: true
      matrix:
        include:
          - sub_level: "25"
            os_patch_level: "2023-10"
          - sub_level: "43"
            os_patch_level: "2023-11"
          - sub_level: "57"
            os_patch_level: "2024-01"
          - sub_level: "68"
            os_patch_level: "2024-03"
          - sub_level: "75"
            os_patch_level: "2024-05"
          - sub_level: "78"
            os_patch_level: "2024-06"
          - sub_level: "84"
            os_patch_level: "2024-07"
          - sub_level: "90"
            os_patch_level: "2024-08"
          - sub_level: "93"
            os_patch_level: "2024-09"
          - sub_level: "99"
            os_patch_level: "2024-10"
          - sub_level: "112"
            os_patch_level: "2024-11"
          - sub_level: "115"
            os_patch_level: "2024-12"
          - sub_level: "118"
            os_patch_level: "2025-01"
          - sub_level: "124"
            os_patch_level: "2025-02"
          - sub_level: "128"
            os_patch_level: "2025-03"
          - sub_level: "129"
            os_patch_level: "2025-04"
          - sub_level: "134"
            os_patch_level: "2025-05"
          - sub_level: "138"
            os_patch_level: "2025-06"
          - sub_level: "141"
            os_patch_level: "2025-07"
          - sub_level: "X"
            os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android14"
      kernel_version: "6.1"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      use_make: ${{ inputs.use_make }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      kernelsu_branch_other: ${{ inputs.kernelsu_branch_other || '' }}
